/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package infinite.zoomer;

import infinite_zoomer.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
    }
}
