/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package infinite_zoomer;

import infinite_zoomer.gui.AbstractGUI;
import infinite_zoomer.gui.HTMLGUI;
import infinite_zoomer.gui.SwingGUI;
import infinite_zoomer.model.DrawingModel;
import infinite_zoomer.server.HTMLServer;
import infinite_zoomer.model.DrawingModel.updateListener;

public class App {
    public static void main(String[] args) {
        DrawingModel model = new DrawingModel();
        HTMLServer server = new HTMLServer(new HTMLGUI(model));
        server.start();

        System.out.printf("Running the server! Go to http://localhost:%d/ !%n", server.getPort());

        var gui = new SwingGUI(model);
        updateListener listener = model.new updateListener();
        listener.addListener(gui);
        gui.initialize();
    }
}
