/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package infinite_zoomer;

import infinite_zoomer.gui.SwingGUI;
import infinite_zoomer.model.DrawingModel;
import infinite_zoomer.server.HTMLServer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        DrawingModel model = new DrawingModel();
        HTMLServer server = new HTMLServer(model);
        server.start();

        var gui = new SwingGUI();
        //gui.initialize();
    }
}
